/**
 * Reveal formatting — ported from formwyn_prototype/reveal.py.
 *
 * Important: the "core" (practical drop — skills, aspects, uniques to
 * chase) and the freshness line are the exact verified text from the
 * class docs, NOT regenerated by the LLM. The LLM is only ever used
 * upstream to read player intent (extraction), never to reword or
 * invent build facts. That split is deliberate: it's what keeps a build
 * page reliably correct even though the matching step is AI-driven.
 */

function formatReveal(build) {
  const freshnessLine =
    build.freshness === 'Confirmed'
      ? `Verified for Season 14 · last checked ${build.last_checked}.`
      : `Early-season pick, still settling in — last checked ${build.last_checked}.`;

  return {
    narrator: build.narrator,
    core: build.core,
    freshnessLine,
    freshnessState: build.freshness,
  };
}

module.exports = { formatReveal };
