/**
 * Reveal formatting for a matched setup recommendation.
 *
 * Important: the "narrator" line and the item list/prices are the exact
 * verified text from the setup data, NOT regenerated by the LLM. The LLM
 * is only ever used upstream to read what the person described (extraction),
 * never to reword or invent product facts or prices. That split is
 * deliberate: it's what keeps a setup recommendation reliably correct even
 * though the matching step is AI-driven.
 */

function formatReveal(setup) {
  const freshnessLine =
    setup.freshness === 'Confirmed'
      ? `Verified pricing and availability · last checked ${setup.last_checked}.`
      : `Prices cross-referenced from current UK listings, not individually re-verified today — last checked ${setup.last_checked}. Always confirm live price at checkout.`;

  return {
    narrator: setup.narrator,
    items: setup.items,
    totalEstimate: setup.totalEstimate,
    freshnessLine,
    freshnessState: setup.freshness,
  };
}

module.exports = { formatReveal };
